/// Flutter icons MyCustomeIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyCustomeIcon
///      fonts:
///       - asset: fonts/MyCustomeIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyCustomeIcon {
  MyCustomeIcon._();

  static const _kFontFam = 'MyCustomeIcon';
  static const _kFontPkg = null;

  static const IconData burger_menu_outline = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burger_menu_solid = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan_qr_rounded = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop_bag = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pot_plant = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
